name = "play-backend"
main = "src/index.ts"
compatibility_date = "2023-10-30"

[vars]
GOOGLE_CLIENT_ID = "73332236335-uh69lkbkeclfkbrj5bk405ru5ou96c8n.apps.googleusercontent.com"
ADMIN_EMAIL = "ashishkushwaha88643@gmail.com"

[[kv_namespaces]]
binding = "KV"
id = "375f31af8c384f73896ae4f607ee2f5e"

[[d1_databases]]
binding = "DB"
database_name = "play-db"
database_id = "f571b209-2d77-4a88-aec2-51e47803bb7e"
